### ISSUE TITLE
AttributeError: module 'snappy' has no attribute 'compress'

### ISSUE THREAD

**Issue by usmcamp0811** [conda-forge/python-snappy-feedstock#8]
I am trying to play around with the datashader examples and when I go to import I get the following errors.. bellow is all the code and entire error message. 

import datashader as ds
import datashader.transfer_functions as tf
import dask.dataframe as dd
import numpy as np
import pandas as pd

RETURN>>>

```
[AttributeError                            Traceback (most recent call last)
<ipython-input-4-d9e8607b1310> in <module>()
----> 1 import datashader as ds
      2 import datashader.transfer_functions as tf
      3 import dask.dataframe as dd
      4 import numpy as np
      5 import pandas as pd

/home/mcamp/anaconda3/lib/python3.5/site-packages/datashader/__init__.py in <module>()
      3 __version__ = '0.3.0'
      4 
----> 5 from .core import Canvas
      6 from .reductions import (count, any, sum, min, max, mean, std, var, count_cat,
      7                          summary)

/home/mcamp/anaconda3/lib/python3.5/site-packages/datashader/core.py in <module>()
      3 import numpy as np
      4 from datashape.predicates import istabular
----> 5 from odo import discover
      6 from xarray import DataArray, align
      7 

/home/mcamp/anaconda3/lib/python3.5/site-packages/odo/__init__.py in <module>()
     63     from .backends.url import URL
     64 with ignoring(ImportError):
---> 65     from .backends.dask import dask
     66 
     67 

/home/mcamp/anaconda3/lib/python3.5/site-packages/odo/backends/dask.py in <module>()
      8 
      9 from dask.array.core import Array, from_array
---> 10 from dask.bag.core import Bag
     11 import dask.bag as db
     12 from dask.compatibility import long

/home/mcamp/anaconda3/lib/python3.5/site-packages/dask/bag/__init__.py in <module>()
      1 from __future__ import absolute_import, division, print_function
      2 
----> 3 from .core import (Bag, Item, from_sequence, from_url, to_textfiles, concat,
      4                    from_delayed, bag_range as range, bag_zip as zip)
      5 from .text import read_text

/home/mcamp/anaconda3/lib/python3.5/site-packages/dask/bag/core.py in <module>()
     39 from ..utils import (open, system_encoding, takes_multiple_arguments, funcname,
     40                      digit, insert)
---> 41 from ..bytes.core import write_bytes
     42 
     43 

/home/mcamp/anaconda3/lib/python3.5/site-packages/dask/bytes/__init__.py in <module>()
      2 
      3 from ..utils import ignoring
----> 4 from .core import read_bytes, open_files, open_text_files
      5 
      6 from . import local

/home/mcamp/anaconda3/lib/python3.5/site-packages/dask/bytes/core.py in <module>()
      7 from warnings import warn
      8 
----> 9 from .compression import seekable_files, files as compress_files
     10 from .utils import SeekableFile, read_block
     11 from ..compatibility import PY2, unicode

/home/mcamp/anaconda3/lib/python3.5/site-packages/dask/bytes/compression.py in <module>()
     30 with ignoring(ImportError):
     31     import snappy
---> 32     compress['snappy'] = snappy.compress
     33     decompress['snappy'] = snappy.decompress
     34 

AttributeError: module 'snappy' has no attribute 'compress'](url)
```

**Comment by mariusvniekerk** [comment]
Can you test with a more modern version from pip? Just want to be sure that upgrading will work

**Comment by usmcamp0811** [comment]
I went searching through the datashader git and found a environment file with all their packages and started just double checking I had everything installed.. not sure what it was but its working now. Below is the list if you wanted to see if there was a possible unlisted dependency.  

```yaml
name: ds
channels:
 - bokeh/label/dev
 - conda-forge
 - ioam/label/dev
 - ioam
 - numba
 - scitools/label/dev

dependencies:
 - attrs
 - bokeh>=0.12.6dev3
 - cartopy
 - colorcet
 - dask
 - datashader
 - dill
 - distributed
 - geoviews
 - holoviews
 - iris
 - jupyter
 - krb5
 - matplotlib
 - networkx
 - numba
 - numpy
 - pandas
 - paramnb
 - pyproj
 - pytables
 - pytest
 - python=3.6
 - rasterio
 - requests
 - scikit-image
 - scipy
 - shapely
 - statsmodels
 - tblib
 - xarray
 - yaml
 - fastparquet
 - snappy
 - python-snappy
 - jupyter_dashboards
 - pip:
   - cachey
```
